name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pdm
        run: |
          pip install pdm

      - name: Install dependencies
        run: |
          pdm install -d

      - name: Run linting
        run: |
          pdm run lint

      - name: Run tests and upload coverage
        run: |
          pdm run test-cov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
